image: python:2.7-jessie
    
stages:
  - test
  - notify
  - deploy

before_script:
  - "pip install pipenv"
  - "pipenv install --dev --system"

run_tests:
  stage: test
  script:
    - "python test/test.py"

notify_build_failure:
  stage: notify
  script:
    - "apt-get update -qq && apt-get install -y -qq curl" 
    - "curl -X POST -d 'message=\"backup_sweeper build failed\"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover"
  when: on_failure

notify_build_success:
  stage: notify
  script:
    - "apt-get update -qq && apt-get install -y -qq curl" 
    - "curl -X POST -d 'message=\"backup_sweeper build successful\"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover"
  when: on_success

deploy_to_home_router:
  stage: deploy
  environment:
    name: "home.michaelhollister.me"
    url: "http://home.michaelhollister.me"
  script:
    - "apt-get update -qq && apt-get install openvpn"
    - "echo -e \"${OPENVPN_CONFIG}\" > home.ovpn"
    - "openvpn --config home.ovpn --daemon"  # connect vpn
    - "sleep 30"  # wait for connection
    - "ping -c 4 ${REMOTE_SERVER}"  # test vpn connection
    - "pyinstaller --distpath bin --onefile src/backup_sweeper.py"  # build executable
    # scp the binary
    - "sshpass -p \"$REMOTE_PASSWORD\" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ./bin/backup_sweeper ${REMOTE_USER}@${REMOTE_SERVER}:/home/michaelhollister/.bin/"
    - "killall openvpn"  # kill vpn connection
  when: on_success
  only: 
    - master
