language: python

sudo: required

services:
  - docker

env: SH="docker exec -t backup_sweeper bash -c"

before_install:
  - "docker run --detach --name backup_sweeper -v $(pwd):/travis -w /travis python:2.7-jessie tail -f /dev/null"
  - "docker ps"

install:
  - "$SH \"pip install pipenv\""
  - "$SH \"pipenv install --dev --system\""

script:
  - $SH "python test/test.py"
