language: python
sudo: required
services:
- docker
env:
- SH="docker exec -t backup_sweeper bash -c"
before_install:
- docker run --detach --name backup_sweeper -v $(pwd):/travis -w /travis python:2.7-slim-stretch
  tail -f /dev/null
- docker ps
addons:
  apt:
    update: true
    packages:
    - openvpn # need for deployment
    - psmisc  # need for killall
  on:
    branch: master
install:
- $SH "pip install pipenv"
- $SH "pipenv install --dev --system"
script:
- $SH "python test/test.py"
after_failure:
- curl -X POST -d 'message="backup_sweeper build failed"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover
after_success:
- curl -X POST -d 'message="backup_sweeper build successful"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover
before_deploy:
- $SH "apt-get update -qy && apt-get install --no-install-recommends -qfy python-dev python-setuptools build-essential"
- openssl aes-256-cbc -K $encrypted_d7fe4871d4a5_key -iv $encrypted_d7fe4871d4a5_iv -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
# setup ssh
- sudo openvpn deploy.ovpn &
- sleep 30
- ping -c 4 $REMOTE_SERVER
- mv id_rsa ~/.ssh/
- sudo chmod 600 ~/.ssh/id_rsa
- ssh-keyscan -H $REMOTE_SERVER > ~/.ssh/known_hosts
# build binary
- $SH "pyinstaller --distpath /travis/bin/ --onefile /travis/src/backup_sweeper.py"
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
after_deploy:
- sudo killall openvpn
