language: python
sudo: required
services:
- docker
env:
- SH="docker exec -t backup_sweeper bash -c"
before_install:
- openssl aes-256-cbc -K $encrypted_d7fe4871d4a5_key -iv $encrypted_d7fe4871d4a5_iv
  -in .travis/deploy.ovpn.enc -out .travis/deploy.ovpn -d
- docker run --detach --name backup_sweeper -v $(pwd):/travis -w /travis python:2.7-slim-stretch
  tail -f /dev/null
- docker ps
addons:
  apt:
    update: true
    packages:
    - openvpn
    - sshpass
    - psmisc
install:
- $SH "pip install pipenv"
- $SH "pipenv install --dev --system"
script:
- $SH "python test/test.py"
after_failure:
- curl -X POST -d 'message="backup_sweeper build failed"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover
after_success:
- curl -X POST -d 'message="backup_sweeper build successful"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@michaelhollister.me/api/pushover
before_deploy:
- ifconfig -a
- openvpn --config .travis/deploy.ovpn &
- sleep 30
- $SH "pyinstaller --distpath bin --onefile src/backup_sweeper.py"
deploy:
  provider: script
  script: sshpass -p "$REMOTE_PASSWORD" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    ./bin/backup_sweeper ${REMOTE_USER}@${REMOTE_SERVER}:/usr/local/bin/backup_sweeper
    && sshpass -p "$REMOTE_PASSWORD" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    ${REMOTE_USER}@${REMOTE_SERVER} /bin/chmod +x /usr/local/bin/backup_sweeper
  on:
    branch: master
after_deploy:
- killall openvpn
